current_os: linux
game_file_extensions:
- gba
- nds
- iso
games_folder: /home/pi/Documents/RemoteGames
server_configs:
  server_ip: null
  server_password: null
  server_port: null
  server_username: null
